# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches: ['main'] # mainブランチにプッシュされたら実行

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: コードを取得
        uses: actions/checkout@v4
      - name: Node.jsをセットアップ
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: パッケージをインストール
        run: npm ci
      - name: プロジェクトをビルド（翻訳）
        run: npm run build
      - name: Pagesの設定
        uses: actions/configure-pages@v4
      - name: 成果物をアップロード
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # Viteが生成するフォルダを指定
      - name: GitHub Pagesへ公開
        id: deployment
        uses: actions/deploy-pages@v4